### PR TITLE
Upgrade to Pydantic 2.5.3 while still using v1 underneath

### PR DESCRIPTION
**Pull request by ddorian**
Fixes https://github.com/mom1/api-client-pydantic/issues/273

### CODE REVIEW

**Comment by ddorian** [comment]
@mom1 what do you think?

**Comment by ddorian** [comment]
If you want to support both versions we can change imports to something like:
```python
try:
    #pydantic2
    import pydantic.v1 as pydantic
except ImportError:
    #pydantic1
    import pydantic
```

**Comment by mom1** [comment]
@ddorian take a look at this #287, what do you think?

**Comment by ddorian** [comment]
Closing since https://github.com/mom1/api-client-pydantic/pull/287 was merged.
Looking forward to the new release.

**Pull request closed without merging**
